<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\sunamo\SunamoCode\SunamoCode.csproj">
    </ProjectReference>
    <ProjectReference Include="..\..\sunamo\Xlf\Xlf.csproj">
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="fmdev.XliffParser">
      <HintPath>..\..\sunamo\dll\net45\fmdev.XliffParser.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\sunamo\Xlf\Xlf.csproj">
      <Project>{00B76D22-B82F-43FD-AC48-4B1F56E6910F}</Project>
      <Name>Xlf</Name>
    </ProjectReference>
  </ItemGroup>
</Project>
